name: dates_generator
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch>=2.2
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1       # remove this line if running CPU-only
  - numpy>=1.26
  - pip
  - pip:
      - matplotlib>=3.8      # for plotting loss curves in the notebook
      - seaborn>=0.13
      - tqdm>=4.66
